config/routes.rb
Rails.application.routes.draw do
  root to: 'cats#index'
  resources :cats
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :breed, presence: true
  has_one_attached :kitty_photo
  before_save(:titleize_cat)

  private
    def titleize_cat
      self.breed = self.breed.titleize
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cats, dependent: :destroy
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end
end

app/controllers/cats_controller.rb
require 'open-uri'

class CatsController < ApplicationController
  before_action :authorize, only: [:new, :edit]

  def index
    @cats = Cat.all
    render :index
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @user = User.find(session[:user_id])
    @cat = @user.cats.new(cat_params)
   
    if @cat.save
      cat_img = CatImage.new(@cat.breed)
      CatImage.get_breeds_array
      @url = cat_img.get_image_url
      url = URI.parse(@url)
      filename = File.basename(url.path)
      file = URI.open(url)
      @cat.kitty_photo.attach(io: file, filename: filename)
      redirect_to cats_path
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def show
    @cat = Cat.find(params[:id])
   
    render :show
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      cat_img = CatImage.new(@cat.breed)
      CatImage.get_breeds_array
      @url = cat_img.get_image_url
      url = URI.parse(@url)
      filename = File.basename(url.path)
      file = URI.open(url)
      @cat.kitty_photo.attach(io: file, filename: filename)
      redirect_to cats_path
    else
      render :edit
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy
    redirect_to cats_path
  end

  private
    def cat_params
      params.require(:cat).permit(:name, :breed)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/edit.html.erb
<% if @cat.user_id == current_user.id %>
<h1>Edit cat</h1>

  <%= form_for @cat do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :breed %>
    <%= f.text_field :breed %>
    <%= f.submit  %>
  <% end %>
<% else %>
  <p>This isn't your cat</p>
<%end%>

<p><%= link_to "Return to cats", cats_path %></p>

app/views/cats/index.html.erb
<h1>Welcome to Beautiful Cats</h1>
<h1>All Cats</h1>
<% if @cats.any? %>
  <ul>
    <% @cats.each do |cat| %>
      <li><%= link_to cat.name, cat_path(cat) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no cats yet.</p>
<% end %>

<% if current_user %>
  <% if current_user.cats.any? %>
    <h3>My Kitties:</h3>
    <% current_user.cats.each do |kitty| %>
      <%= link_to kitty.name, cat_path(kitty) %>
    <% end %>
  <% else %>
    <p>You have no kitties.</p>
  <% end %>
<% end %>

<p><%= link_to "Add a new cat", new_cat_path %></p>

app/views/cats/new.html.erb
  <h1>New cat</h1>

  <%= form_for @cat do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :breed %>
    <%= f.text_field :breed %>
    <%= f.submit  %>
  <% end %>
  <p>Please log in to add your cats</p>

app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
<h3><%= @cat.breed %></h3>
<% if @cat.kitty_photo %>
  <%= image_tag(@cat.kitty_photo, {:style => "width:400px;"}) %>
<% else %>
  <p>No image for this kitty</p>
<% end %>

<% if (current_user) && (@cat.user_id == current_user.id) %>
<p><%= link_to "Edit", edit_cat_path(@cat) %></p>
  <p><%= link_to "Delete cat", cat_path(@cat),
                          :data => {:confirm => "Are you sure?",
                                        :method => "delete"} %></p>
<% end %>
<p><%= link_to "Return to cats", cats_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatPics</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if current_user %>
      <%= current_user.email %> | <%= link_to "Sign out", '/signout' %>
    <% else %>
      <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
    <% end %>

    <%= flash[:alert] %>
    <%= flash[:notice] %>
    
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>